site_name: Musical Notes
repo_url: https://github.com/drigols/musical-notes
repo_name: drigols/musical-notes
edit_uri: tree/master/docs

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: black

markdown_extensions:
  - attr_list # Allow apply styles ![](){width=xxx .center}.

extra_css:
  - stylesheets/extra.css
